sudo: required 
services:
  - docker 


before_install:
  - docker build -t rukmanibhagat/docker-react -f Dockerfile.dev .

script:
  - docker run rukmanibhagat/docker-react npm run test -- --coverage  
